SELECT * FROM super_store_sales_data.train;
desc train;
select * from train;
-- DATE COLUMN → Time-based Analysis
/*
Business Questions:

When is performance good or bad?

Is there seasonality?

Are sales growing over time?
*/
select `Order Date` from train limit 5;

set SQL_SAFE_UPDATES=0;

update train set `Order Date`=STR_TO_DATE(`Order Date`, '%d/%m/%Y');

update train set `Ship Date`=STR_TO_DATE(`Ship Date`, '%d/%m/%Y');

-- With this query we get to know total sales of each month

select MONTH(`Order Date`) as Month,
round(sum(sales),2) as Total_sales 
from train
group by MONTH(`Order Date`)
order by MONTH(`Order Date`);

-- SALES / REVENUE COLUMN → Growth & Performance
/*
Business Questions

Are we growing or declining?

Which products drive revenue?

🛠️ Operations

SUM, AVG

Ranking (TOP / BOTTOM)

Growth comparison
*/

-- With this query we can know total_revenue generated by each category
select category,round(sum(sales),1) as total_revenue 
from train group by category order by total_revenue desc;

-- With this query we can know average sales  by each category

select category,round(avg(sales),1) as total_revenue 
from train group by category order by total_revenue desc;

select distinct(category) from train;

-- Checking unique product names and their total sales

select distinct(`Product Name`),sum(sales) as total_sales
from train group by `Product Name`;

-- CUSTOMER COLUMN → Customer Behavior Analysis

/*
Business Questions

Who are our best customers?

Who buys only once?

Who is likely to churn?

🛠️ Operations

COUNT orders per customer

SUM sales per customer

Segmentation
*/

select distinct(`Customer Name`),count(`Customer Name`) as freq,
round(sum(sales),1) as total_sales from train
group by `Customer Name` order by freq desc;

-- REGION / LOCATION COLUMN → Regional Analysis

/*
Business Questions

Where are we underperforming?

Which region needs attention?

🛠️ Operations

Region-wise aggregation

Performance comparison
*/
select region,round(sum(sales),1)  as total_sales
from train group by region order by total_sales desc;

-- Write query to get which customer buys most frequently and what his total sales

select distinct(`Customer Name`),count(`Customer Name`) as freq,
round(sum(sales),1) as total_sales from train
group by `Customer Name` order by freq desc limit 1;

-- Top 3 sales from the train dataset

select * from train
order by sales desc limit 3;	

-- Calculate the average order value per customer

select `Customer ID`,avg(sales) as Avg_order_value
from train group by `Customer ID`;

-- Calculate the max orders by region and category

select region,Category,round(max(total_sales),1)as max_sales
from (
select region,category,sum(sales) as total_sales
from train group by Region,Category
) as subquery group by Region,Category;

-- Calculate quantity of total products in region

select region,category,count(`Customer ID`) as cust_count
from train group by region,category;

-- calculate count and total sales of each category in each month

select extract(month from `Order Date`) as month,category,
count(`Customer ID`) as cust_count,round(sum(sales),1)
from train group by month,category order by month;

-- write sql to count total no of orders

select count(*) from train;

-- write sql query  to calculate quantity and total_revenue of ship mode

select `Ship Mode`,count(*),round(sum(sales),1) as total_revenue from train 
group by `Ship Mode`;

-- write sql query to check details on 2017-11-11

select * from train where date(`Order Date`) = '2017-11-08';

-- write sql query unique Sub-Category and their total orders and total_revenue generated

select distinct(`Sub-Category`),count(`Sub-Category`) as quantity,
round(sum(sales),1) as total_revenue from train
group by `Sub-Category` order by quantity desc;

-- Montly trend analysis

select YEAR(`Order Date`) as year,MONTH(`Order Date`) as month,
round(sum(sales),1) from train group by 1,2 order by 1,2 asc;
-- Rank categories by sales

select category ,round(sum(sales),1) as total_sales ,
rank() over(order by sum(sales) desc) as sales_rank
from train group by category;

-- Find Missing Values 

select * from train
where sales is null
or `Order Date` is null
or `Customer Name` is null;


